### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Player005/BetterAddServer#1]
https://mclo.gs/xdF7mdC

**Comment by Player005** [comment]
Sorry for not responding in such a long time, this repository was a bit inactive for some time, however there is a new release where I rewrote all the mixins so this crash should now be fixed. Sorry again!

**Comment by Aces-and-Jacks** [comment]
https://mclo.gs/pJfnINb still crashes on 1.19.2. Tho I see on the name it specifies 1.19.4 so maybe, if you want to, you could specify that in the version number?

**Comment by Player005** [comment]
Thanks for the info, I can look into this tomorrow. I am currently not sure if I want to support 1.19.2 as it's an additional version to maintain, but if it's easy to fix I might do it, otherwise I'll specify it is 1.19.4/1.20 only.

**Comment by Player005** [comment]
Alright, released a 1.19.2 version
https://modrinth.com/mod/betteraddserver/version/1.0.1-1.19.2

**Comment by Aces-and-Jacks** [comment]
Thanks so much for the fix
